# Generated by Django 5.1 on 2024-08-17 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="book_id",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="borrowing",
            old_name="user_id",
            new_name="user",
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("PAID", "Paid")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PAYMENT", "Payment"), ("FINE", "Fine")],
                        max_length=20,
                    ),
                ),
                ("session_url", models.URLField(blank=True)),
                ("session_id", models.TextField(blank=True)),
                ("money_to_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "borrowing_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="borrowings_service.borrowing",
                    ),
                ),
            ],
        ),
    ]
