# Generated by Django 5.1 on 2024-08-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings_service", "0004_alter_borrowing_actual_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[("PAYMENT", "Payment"), ("FINE", "Fine")],
                default="PAYMENT",
                max_length=20,
            ),
        ),
    ]
