# Generated by Django 5.1 on 2024-08-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "borrowings_service",
            "0006_alter_payment_session_id_alter_payment_session_url",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="money_to_pay",
        ),
    ]
